version: '3.4'

services:
  helpdesk.db:
    volumes:
      - ./.containers/sqlserver:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password

  helpdesk.mq:
    hostname: helpdesk-mq-master
    # volumes:
    #   - ./.containers/rabbitmq/data/:/var/lib/rabbitmq
    #   - ./.containers/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  helpdesk.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=helpdesk
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/helpdesk.pfx
      - ConnectionStrings__HelpDeskDb=Server=helpdesk.db,1433;Database=HelpDeskDb;User=sa;Password=yourStrong(!)Password;Encrypt=False;
      - Jwt__Issuer=https://helpdesk.apigateway/
      - Jwt__Audience=https://helpdesk.apigateway/
      - Jwt__Security=WvvWzuqwJ5DvDGaRRVnKCuL2k35aEhiY0qoKR7qj0gVn3f6PxwPnhbB2VPp82gLH
      - Jwt__TokenExpirationInMinutes=60
    depends_on:
      - helpdesk.db
      - helpdesk.consumerservice.api
      - helpdesk.producerservice.api
    ports:
      - "5000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./docker/aspnet/https:/root/.aspnet/https:ro

  helpdesk.consumerservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=helpdesk
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/helpdesk.pfx
      - ConnectionStrings__HelpDeskDb=Server=helpdesk.db,1433;Database=HelpDeskDb;User=sa;Password=yourStrong(!)Password;Encrypt=False;
      - Jwt__Issuer=https://helpdesk.apigateway/
      - Jwt__Audience=https://helpdesk.apigateway/
      - Jwt__Security=WvvWzuqwJ5DvDGaRRVnKCuL2k35aEhiY0qoKR7qj0gVn3f6PxwPnhbB2VPp82gLH
      - Jwt__TokenExpirationInMinutes=60
      - MessageBroker__Host=amqp://helpdesk.mq:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
    depends_on:
      - helpdesk.db
      - helpdesk.mq
    ports:
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./docker/aspnet/https:/root/.aspnet/https:ro

  helpdesk.producerservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=helpdesk
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/helpdesk.pfx
      - ConnectionStrings__HelpDeskDb=Server=helpdesk.db,1433;Database=HelpDeskDb;User=sa;Password=yourStrong(!)Password;Encrypt=False;
      - Jwt__Issuer=https://helpdesk.apigateway/
      - Jwt__Audience=https://helpdesk.apigateway/
      - Jwt__Security=WvvWzuqwJ5DvDGaRRVnKCuL2k35aEhiY0qoKR7qj0gVn3f6PxwPnhbB2VPp82gLH
      - Jwt__TokenExpirationInMinutes=60
      - MessageBroker__Host=amqp://helpdesk.mq:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - UserApiService__Url=https://helpdesk.apigateway/users/
      - UserApiService__Timeout=60
      - CategoryApiService__Url=https://helpdesk.consumerservice.api/categories/
      - CategoryApiService__Timeout=60
      - TicketApiService__Url=https://helpdesk.consumerservice.api/tickets/
      - TicketApiService__Timeout=60
    depends_on:
      - helpdesk.db
      - helpdesk.mq
      - helpdesk.consumerservice.api
    ports:
      - "5002:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./docker/aspnet/https:/root/.aspnet/https:ro
