name: tc-fase3-microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '7.0.x'
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore TechChallenge.sln

      - name: Build
        run: dotnet build TechChallenge.sln --no-restore

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore TechChallenge.sln

      - name: Build
        run: dotnet build TechChallenge.sln --no-restore

      - name: UnitTests - HelpDesk.ApiGateway
        run: dotnet test tests/HelpDesk.ApiGateway.Application.UnitTests/HelpDesk.ApiGateway.Application.UnitTests.csproj --no-build --verbosity normal

      - name: UnitTests - HelpDesk.ConsumerService
        run: dotnet test tests/HelpDesk.ConsumerService.Application.UnitTests/HelpDesk.ConsumerService.Application.UnitTests.csproj --no-build --verbosity normal

      - name: UnitTests - HelpDesk.ProducerService
        run: dotnet test tests/HelpDesk.ProducerService.Application.UnitTests/HelpDesk.ProducerService.Application.UnitTests.csproj --no-build --verbosity normal

  architecture-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore TechChallenge.sln

      - name: Build
        run: dotnet build TechChallenge.sln --no-restore

      - name: ArchitectureTests - HelpDesk.ApiGatewayService
        run: dotnet test tests/HelpDesk.ApiGatewayService.ArchitectureTests/HelpDesk.ApiGateway.ArchitectureTests.csproj --no-build --verbosity normal

      - name: ArchitectureTests - HelpDesk.ConsumerService
        run: dotnet test tests/HelpDesk.ConsumerService.ArchitectureTests/HelpDesk.ConsumerService.ArchitectureTests.csproj --no-build --verbosity normal

      - name: ArchitectureTests - HelpDesk.ProducerService
        run: dotnet test tests/HelpDesk.ProducerService.ArchitectureTests/HelpDesk.ProducerService.ArchitectureTests.csproj --no-build --verbosity normal

  integration-tests:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - uses: actions/cache@v3
          with:
            path: ${{ env.NUGET_PACKAGES }}
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
            restore-keys: |
              ${{ runner.os }}-nuget-

        - name: Restore dependencies
          run: dotnet restore TechChallenge.sln

        - name: Build
          run: dotnet build TechChallenge.sln --no-restore

        - name: IntegrationTests - HelpDesk.ApiGateway
          run: dotnet test tests/HelpDesk.ApiGateway.IntegrationTests/HelpDesk.ApiGateway.IntegrationTests.csproj --no-build --verbosity normal

        - name: IntegrationTests - HelpDesk.ConsumerService
          run: dotnet test tests/HelpDesk.ConsumerService.Api.IntegrationTests/HelpDesk.ConsumerService.Api.IntegrationTests.csproj --no-build --verbosity normal
